# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool: 'AWS'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'NodeJS Build'

- script: |
    npm install --save jslint
    node_modules/.bin/jslint --edition=latest "*.js" || true
  displayName: 'NodeJS Lint'

- task: CmdLine@2
  inputs:
    script: |
      mkdir publish
      mv node_modules server.js publish
      cd publish
      az artifacts universal publish --organization https://dev.azure.com/DevOps-Batches/ --project="DevOps48" --scope project --feed RoboShop --name  $(appName) --version 1.0.$(Build.BuildId) --description "$(appName)" --path .
  displayName: Publish Artifacts

variables:
  appName: "user"